stages:
  - test
  - release

.build_template: &build
  script:
    - mkdir -p ${GOPATH}/src/git.darmstadt.ccc.de/ffda
    - ln -rs ../fastd-exporter ${GOPATH}/src/git.darmstadt.ccc.de/ffda/
    - cd ${GOPATH}/src/git.darmstadt.ccc.de/ffda/fastd-exporter
    - go fmt
    - git diff --exit-code
    - go get ./...
    - go build
    - ls -lah fastd-exporter

test:
  <<: *build
  image: $IMAGE
  parallel:
    matrix:
      - IMAGE:
        - 'golang:1.19' # debian 12
        # last two releases; https://go.dev/doc/devel/release
        - 'golang:1.20'
        - 'golang:1.21'

release:
  <<: *build
  stage: release
  image: golang:latest

  artifacts:
    paths:
      - fastd-exporter

