name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [
          '1.21'
        ]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Display Go version
      run: go version

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: run go fmt
      run: go fmt

    - name: check for changes due to fmt
      run: git diff --exit-code
